# Generated by metatavu-secrets-cli's release workflow. Do not edit by hand.
class Msecrets < Formula
  desc "Metatavu Secrets: set up, run and understand hosting secrets"
  homepage "https://github.com/Metatavu/metatavu-secrets"
  version "0.1.0"

  on_macos do
    # No Intel build: Apple stopped shipping those Macs in 2023. Rosetta
    # translates x86 to arm, not the reverse, so there is nothing to fall back to.
    depends_on arch: :arm64

    url "https://github.com/Metatavu/homebrew-tap/releases/download/msecrets-v0.1.0/msecrets-darwin-arm64.tar.gz"
    sha256 "4ea883ecb8ccb5b347a655051c34d2104ccccbe9de206337813be15901d512a8"
  end

  on_linux do
    on_intel do
      url "https://github.com/Metatavu/homebrew-tap/releases/download/msecrets-v0.1.0/msecrets-linux-amd64.tar.gz"
      sha256 "17da1a01cc5f9bd580460e486a0f90b1c5ddd33e2ca452b731c371b563e3d5cb"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Metatavu/homebrew-tap/releases/download/msecrets-v0.1.0/msecrets-linux-arm64.tar.gz"
      sha256 "ec4af5699cc55cdc9c61bb950ff28253b19362bc60eb8db11d89343b4f850c18"
    end
  end


  def install
    bin.install "msecrets"
  end

  def caveats
    <<~EOS
      Sign in for anything acting on your behalf:

        msecrets auth login

      It talks to https://secrets.metatavu.io by default; MSECRETS_SERVER_URL or
      --server override that.
    EOS
  end

  test do
    assert_match "msecrets #{version}", shell_output("#{bin}/msecrets --version")
    # With no credentials this exits 3, "authentication required".
    shell_output("#{bin}/msecrets auth status --local", 3)
  end
end
