# Generated by severa-cli's release workflow. Do not edit by hand.
class Severa < Formula
  desc "Controlled access to Severa for people, CI and agents"
  homepage "https://github.com/Metatavu/severa-cli"
  version "0.3.0"

  on_macos do
    # No Intel build: Apple stopped shipping those Macs in 2023. Rosetta
    # translates x86 to arm, not the reverse, so there is nothing to fall back to.
    depends_on arch: :arm64

    url "https://github.com/Metatavu/homebrew-tap/releases/download/severa-v0.3.0/severa-darwin-arm64.tar.gz"
    sha256 "203f48f9e86ce09d6c0bb857f81c533301f6853f878019fae9fbd77d1b6e995a"
  end

  on_linux do
    on_intel do
      url "https://github.com/Metatavu/homebrew-tap/releases/download/severa-v0.3.0/severa-linux-amd64.tar.gz"
      sha256 "216b96c066f7dfd3b369cf32184be22d19a319a2e872c4b18d76dc8988990553"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Metatavu/homebrew-tap/releases/download/severa-v0.3.0/severa-linux-arm64.tar.gz"
      sha256 "b012c8efab8ff7a19228010bb7080735d0789676be1714099e56b2568195244f"
    end
  end


  def install
    bin.install "severa"
  end

  def caveats
    <<~EOS
      Sign in for anything acting on your behalf:

        severa auth login

      It talks to the deployed gateway by default; SEVERA_GATEWAY_URL or
      --gateway override that.
    EOS
  end

  test do
    assert_match "severa #{version}", shell_output("#{bin}/severa --version")
    # With no credentials this exits 3, "authentication required".
    shell_output("#{bin}/severa auth status --local", 3)
  end
end
