# Generated by severa-cli's release workflow. Do not edit by hand.
class Severa < Formula
  desc "Controlled access to Severa for people, CI and agents"
  homepage "https://github.com/Metatavu/severa-cli"
  version "0.5.0"

  on_macos do
    # No Intel build: Apple stopped shipping those Macs in 2023. Rosetta
    # translates x86 to arm, not the reverse, so there is nothing to fall back to.
    depends_on arch: :arm64

    url "https://github.com/Metatavu/homebrew-tap/releases/download/severa-v0.5.0/severa-darwin-arm64.tar.gz"
    sha256 "996cea4126cacadfbcf8c5ca1512e50e3b33e2852e8f41795b0f1dca6507073d"
  end

  on_linux do
    on_intel do
      url "https://github.com/Metatavu/homebrew-tap/releases/download/severa-v0.5.0/severa-linux-amd64.tar.gz"
      sha256 "55c6b02d6136040e17db461c4b744984bef6969c441528bc0844a71db5366249"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Metatavu/homebrew-tap/releases/download/severa-v0.5.0/severa-linux-arm64.tar.gz"
      sha256 "ece951253d46bc627b8fcd785367880428a00a7d50ebfb861b71e80536589056"
    end
  end


  def install
    bin.install "severa"
  end

  def caveats
    <<~EOS
      Sign in for anything acting on your behalf:

        severa auth login

      It talks to the deployed gateway by default; SEVERA_GATEWAY_URL or
      --gateway override that.
    EOS
  end

  test do
    assert_match "severa #{version}", shell_output("#{bin}/severa --version")
    # With no credentials this exits 3, "authentication required".
    shell_output("#{bin}/severa auth status --local", 3)
  end
end
