# Generated by severa-cli's release workflow. Do not edit by hand.
class Severa < Formula
  desc "Controlled access to Severa for people, CI and agents"
  homepage "https://github.com/Metatavu/severa-cli"
  version "0.4.0"

  on_macos do
    # No Intel build: Apple stopped shipping those Macs in 2023. Rosetta
    # translates x86 to arm, not the reverse, so there is nothing to fall back to.
    depends_on arch: :arm64

    url "https://github.com/Metatavu/homebrew-tap/releases/download/severa-v0.4.0/severa-darwin-arm64.tar.gz"
    sha256 "576e5b577c6a8946b7a38b0535e38e756eaacdaa41532694c928df76976a8a75"
  end

  on_linux do
    on_intel do
      url "https://github.com/Metatavu/homebrew-tap/releases/download/severa-v0.4.0/severa-linux-amd64.tar.gz"
      sha256 "c6a661997fa223843234459c1ac6a88d18f61b1277f369f160463500c44e0286"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Metatavu/homebrew-tap/releases/download/severa-v0.4.0/severa-linux-arm64.tar.gz"
      sha256 "9b8070b09e96f3caad084a8b4611416ca307a195afd4ccad0911b233902e53fd"
    end
  end


  def install
    bin.install "severa"
  end

  def caveats
    <<~EOS
      Sign in for anything acting on your behalf:

        severa auth login

      It talks to the deployed gateway by default; SEVERA_GATEWAY_URL or
      --gateway override that.
    EOS
  end

  test do
    assert_match "severa #{version}", shell_output("#{bin}/severa --version")
    # With no credentials this exits 3, "authentication required".
    shell_output("#{bin}/severa auth status --local", 3)
  end
end
